### ISSUE TITLE
Prefer referencing EF as NuGet packages, not code

### ISSUE THREAD

**Issue by markdstafford** [QingshuChen/RESTier-CLI#1]
Commit #8068540 seems a bit extreme. It includes over 7,000 files from EF and XML source code. We should strive to include only the code we are actually modifying, everything else should be a NuGet package if possible.

**Comment by Lingxi-Li** [comment]
We're using a private modified EF which should be treated as a whole. It may be problematic for part of it to be private modified version while the others come from the official release. The parts may not be compatible. It may be best to use a private trimmed build of EF, or just not to tamer with the official release at all and reference the NuGet packages directly (which I think is not an option in our particular case).

**Comment by QingshuChen** [comment]
We've removed most of useless files in the EF.
